### ISSUE TITLE
I have an issue

### ISSUE THREAD

**Issue by adiprerepa** [kalkulator413/album-gen-py#1]
Your code doesn't work.

**Comment by kalkulator413** [comment]
Could you elaborate on this?

**Comment by kalkulator413** [comment]
Sorry for closing it. Looks like the issue isn't resolved.

**Comment by adiprerepa** [comment]
It's not resolved.

**Comment by kalkulator413** [comment]
Neither is my immigration status.

**Comment by kalkulator413** [comment]
### _**Ok.**_

**Comment by adiprerepa** [comment]
![image](https://user-images.githubusercontent.com/43913660/183278610-47c819bc-0a22-4bbc-af75-1ba6a41e0f50.png)
