### ISSUE TITLE
I have another issue

### ISSUE THREAD

**Issue by adiprerepa** [kalkulator413/album-gen-py#2]
Can you fix your code? It doesn't work.

**Comment by kalkulator413** [comment]
Try [this](https://open.spotify.com/album/5M9SijJoRgczSknq2LaHJN?si=ne4RZv7NRqiBvXqKpnasMg)

**Comment by adiprerepa** [comment]
@kalkulator413 I don't enjoy mediocre music. maybe you do, and that's okay.

**Comment by kalkulator413** [comment]
@adiprerepa I'm terribly hurt by this.

**Comment by adiprerepa** [comment]
cry about it
