### ISSUE TITLE
Can you fix my issue?

### ISSUE THREAD

**Issue by adiprerepa** [kalkulator413/album-gen-py#3]
Why would you specify "Dark"Amber? https://github.com/kalkulator413/album-gen-py/blob/main/main.py#L12

**Comment by kalkulator413** [comment]
Get therapy

**Comment by adiprerepa** [comment]
Do you like dark amber more than the other colors? its not the most appealing theme, gruvbox better imo

**Comment by kalkulator413** [comment]
Sure! Create a pull request and I can change the theme.

**Comment by adiprerepa** [comment]
What's that?
