### ISSUE TITLE
HTML Parser is absolutely trash

### ISSUE THREAD

**Issue by adiprerepa** [kalkulator413/album-gen-py#4]
You should consider using a library, this is a pretty neandrathal-ish way of parsing html. Please fix ASAP, this is clear tech debt.

https://github.com/kalkulator413/album-gen-py/blob/main/scraper.py#L87

**Comment by kalkulator413** [comment]
I would rather scrape with Regex than use a library like Beautiful Soup

**Comment by adiprerepa** [comment]
drink the soup, kalkin

**Comment by kalkulator413** [comment]
I don't quite enjoy soup. Once I drank soup too fast and it burnt my tongue. Since soup typically has such a high temperature it can be very harmful. You should not combine hot liquids with computers. If you have any recommendations for getting used to soup that would be very much appreciated.

**Comment by adiprerepa** [comment]
u bad fr
