### ISSUE TITLE
Request Header specification?

### ISSUE THREAD

**Issue by adiprerepa** [kalkulator413/album-gen-py#5]
Why would you specify your header as windows in https://github.com/kalkulator413/album-gen-py/blob/main/scraper.py#L10?

The API is going to think you're a loser.

**Comment by kalkulator413** [comment]
I'm sorry but WSL >>>>

**Comment by adiprerepa** [comment]
you're going to need to specify what that acronym stands for.

**Comment by kalkulator413** [comment]
WSL (Windows (a group of several proprietary graphical operating system families developed and marketed by Microsoft) Subsystem (a self-contained system within a larger system) Linux (Linux is a family of open-source Unix-like operating systems based on the Linux kernel, an operating system kernel first released on September 17, 1991, by Linus Torvalds))

**Comment by adiprerepa** [comment]
subsystem? more like Dubsystem
