### ISSUE TITLE
Documentation Technical Debt

### ISSUE THREAD

**Issue by adiprerepa** [kalkulator413/album-gen-py#6]
Why does the function `clean_name(string)` have no documentation? How is the reader supposed to understand the underlying mechanism? You should really document your code, because some people have better things to do with their life than look at the documenation for the dependent functions.

https://github.com/kalkulator413/album-gen-py/blob/main/scraper.py#L132

**Comment by kalkulator413** [comment]
It cleans the name

**Comment by adiprerepa** [comment]
i don't know how i feel about that...
