### ISSUE TITLE
Why is this a separate module?

### ISSUE THREAD

**Issue by adiprerepa** [kalkulator413/album-gen-py#7]
It doesn't make sense that `genres.py` is a separate file...https://github.com/kalkulator413/album-gen-py/blob/main/genres.py#L6

I don't understand why you would even do this, it's pretty bad practice.

**Comment by kalkulator413** [comment]
It's just makes a set by reading huge file of genres so that you can quickly check whether the user-inputted genre is valid. I'm terribly sorry if it ruined your day

**Comment by adiprerepa** [comment]
i'm unfollowing you.

**Comment by kalkulator413** [comment]
I'm going to cry while listening to my Vinyl Copy of Bjork's 2001 art-pop masterpiece _Vespertine_. You should check it out once you're done being a miserly snob on https://github.com

**Comment by adiprerepa** [comment]
*Vespertine* is a mid album, you should consider deleting your Spotify account.
